version: '3.2'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/:/freezer/
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      .env
    command: venv/bin/python run.py
  db:
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
