version: '3.2'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/:/freezy/
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      .env
    command: venv/bin/python run.py
